name: Build EXE and Mac Binary

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install build tools on macOS
        if: matrix.os == 'macos-latest'
        run: |
          brew update
          brew install cython
          xcode-select --install || true

      - name: Install numpy and cython first
        run: |
          python -m pip install --upgrade pip
          pip install numpy cython

      - name: Install other dependencies
        run: |
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build binary with pyinstaller
        run: |
          pyinstaller main.py --onefile

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-binary
          path: dist/
